### ISSUE TITLE
Unsuccessful image reconstruction

### ISSUE THREAD

**Issue by coolbunnyx** [lucidrains/magvit2-pytorch#25]
I am running into almost the same issue as the closed thread https://github.com/lucidrains/magvit2-pytorch/issues/12. Not sure how it ended up being resolved. Turning off GAN does not help. Any suggestions are greatly appreciated! Thanks.

The reconstructed images look like these:
![3](https://github.com/lucidrains/magvit2-pytorch/assets/45907990/9e8e989f-9841-40d7-98e0-8ab85486e54a)
![4](https://github.com/lucidrains/magvit2-pytorch/assets/45907990/a4f7568f-aa3b-464f-9a87-7d4904fa0157)

**Comment by coolbunnyx** [comment]
Somehow solved it by doing some normalization stuffs. Not entirely sure about the result since the MLM transformer part remain unfinished.

**Comment by rubbybbs** [comment]
@coolbunnyx Hi! Do you mind kindly sharing how you solve it :-) ?

**Comment by nangying1112** [comment]
@coolbunnyx Hi, I met the same problem. Could you please kindly share your solution?
