### ISSUE TITLE
expired discord invitation

### ISSUE THREAD

**Issue by xyzhang626** [lucidrains/magvit2-pytorch#26]
Hey @lucidrains and guys, I'm working on reproduce this tokenizer and would like to join the discussion. Could you update the discord invitation link? Thanks in advance!

**Comment by lucidrains** [comment]
hmm, i was able to get in

can you screenshot it saying it has expired?

**Comment by xyzhang626** [comment]
sorry for bothering I just checked again it might be my IP issue. Thanks @lucidrains for the great work!

**Comment by lucidrains** [comment]
@xyzhang626 no problem! go train something amazing :)
