### ISSUE TITLE
Example for Images

### ISSUE THREAD

**Issue by jpfeil** [lucidrains/magvit2-pytorch#3]
I'm excited to apply this model to image data. I was wondering if you could give a trivial example for how to apply this library to individual images instead of video. Thank you!

**Comment by lucidrains** [comment]
@jpfeil hey Jacob! thanks for your interest

you can pretrain on images by setting the `dataset_type` to `images` https://github.com/lucidrains/magvit2-pytorch/commit/ec2696d55f0c4cb1028b258e621ed207873fc7b1

**Comment by lucidrains** [comment]
🤔 i need to take my dog down to Santa Cruz at some point for a hike, and for the boardwalk of course
