### ISSUE TITLE
About GroupNorm described in the MAGVIT V2 paper

### ISSUE THREAD

**Issue by sen-ye** [lucidrains/magvit2-pytorch#41]
Hello, thanks for your nice work. I notice that there are some differences between your implementations and original paper. One notable difference is the use of group normalization in the original paper. From my understanding, directly applying group normalization to a 5D video tensor (B, C, T, H, W) can result in non-causal behaviors. In your implementation, you did not include group normalization. Could you please explain your reasoning behind this choice? Is it related to the issue I mentioned?

**Comment by Jason3900** [comment]
Typically you just have to pack B, T to one dimension and do the normal group norm, then you rearrange it back to the original dim.
