### ISSUE TITLE
Is this a bug at magvit2_pytorch.py#L1340?

### ISSUE THREAD

**Issue by AIWanderer-X** [lucidrains/magvit2-pytorch#43]
https://github.com/lucidrains/magvit2-pytorch/blob/f2027d2a99872d38a52c90247c8fb9e51a347198/magvit2_pytorch/magvit2_pytorch.py#L1340

`has_cond` is just a temporary variable that resets and changes its value in the for loop. I guess it should be `self.has_cond` in this line?

**Comment by lucidrains** [comment]
@AIWanderer-X 🤦 thank you for catching this!
