### ISSUE TITLE
Maybe a small bug at magvit2_pytorch.py#L1236?

### ISSUE THREAD

**Issue by AIWanderer-X** [lucidrains/magvit2-pytorch#44]
https://github.com/lucidrains/magvit2-pytorch/blob/e085ec3c13cbef9c1048a7d11e0394b77dc8e6c8/magvit2_pytorch/magvit2_pytorch.py#L1236

I noticed `dim_cond` is added into `FeedForward` with the block under `elif layer_type == 'attend_time':`. Shouldn't it be added into the block under `elif layer_type == 'cond_attend_space':` where `dim_cond` is currently missing in `FeeForward`?

**Comment by lucidrains** [comment]
@AIWanderer-X indeed! thank you again!
