### ISSUE TITLE
using different samples for gan generator and discriminator

### ISSUE THREAD

**Issue by teou** [lucidrains/magvit2-pytorch#8]
Thank you for your great work!

I noticed that when training, the generator and discriminator are using different samples from the same dataloader:
    generator:
        https://github.com/lucidrains/magvit2-pytorch/blob/main/magvit2_pytorch/trainer.py#L289
    discriminator:
        https://github.com/lucidrains/magvit2-pytorch/blob/main/magvit2_pytorch/trainer.py#L327

is this by design?

**Comment by lucidrains** [comment]
@teou yea, so actually it is actually intentional, as when i used to build GANs, i've tried it this way but didn't see better results

do you know if in the paper they did it the way you describe? and are there papers that show this makes a difference?

**Comment by lucidrains** [comment]
another thing you will notice is that i try to use grad penalty in most GAN systems, even though current crop of researchers have mostly forgotten about it. i've tried a bunch of other ways (spec norm or whatever) and never saw good results

**Comment by teou** [comment]
no , i haven't done any experiments yet. 
from other implementations , seems generator and discriminator is consuming the same sample from dataloader, that's how i got confused. ^_^

for example here:
https://github.com/dome272/VQGAN-pytorch/blob/main/training_vqgan.py#L55

**Comment by lucidrains** [comment]
@teou yup i know Dominic, very smart kid! yea, i can take a peek at Robin's original implementation and if he did it that way. if he did, we can do that as well

**Comment by lucidrains** [comment]
@teou yup i know Dominic, very smart kid! i can take a peek at Robin's original implementation tomorrow and see if he did it the way you described. if he did, then let's just do that. however i don't think it makes that big of a difference either way
